version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows

# Docker 构建配置
dockers:
  - image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:{{.Version}}-amd64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{.ProjectName}}"
  - image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:{{.Version}}-arm64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{.ProjectName}}"

docker_manifests:
  - name_template: ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:{{.Version}}
    image_templates:
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:{{.Version}}-amd64
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:{{.Version}}-arm64
  - name_template: ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:latest
    image_templates:
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:latest-amd64
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/{{ tolower .ProjectName }}:latest-arm64

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS_{{ .Arch }}
      {{- else if and (eq .Os "windows") (eq .Arch "amd64") }}{{ title .Os }}
      {{- else }}{{ title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
